# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://computational-materials-ucr.github.io
title: Grad Students in Computational Materials
email: compmatucr@gmail.com
author: Sarah Allec
description: "Computational Materials Research Group Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/computational-materials-ucr  
  - icon: envelope-o
    title: email
    url: mailto:compmatucr@gmail.com
#  - icon: linkedin
#    title: linkedin
#    url: https://www.linkedin.com/in/dcassol/
#  - icon: file-pdf-o
#    title: CV
#    url: img/CassolDanielaCV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
  - icon: facebook
    title: facebook
    url: https://twitter.com/danicassol

